# Install script for directory: C:/Users/skinny/projects/lightspark/lib/llvm-2.7

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files/LLVM")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "C:/Users/skinny/projects/lightspark/lib/llvm-2.7/include/" FILES_MATCHING REGEX "/[^/]*\\.def$" REGEX "/[^/]*\\.h$" REGEX "/[^/]*\\.td$" REGEX "/[^/]*\\.inc$" REGEX "/\\.svn$" EXCLUDE)
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/include/" FILES_MATCHING REGEX "/[^/]*\\.def$" REGEX "/[^/]*\\.h$" REGEX "/[^/]*\\.gen$" REGEX "/[^/]*\\.inc$" REGEX "/cmakefiles$" EXCLUDE REGEX "/\\.svn$" EXCLUDE)
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Support/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/System/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/utils/TableGen/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/include/llvm/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/VMCore/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/CodeGen/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/CodeGen/SelectionDAG/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/CodeGen/AsmPrinter/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Bitcode/Reader/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Bitcode/Writer/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Transforms/Utils/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Transforms/Instrumentation/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Transforms/InstCombine/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Transforms/Scalar/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Transforms/IPO/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Transforms/Hello/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Linker/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Analysis/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Analysis/IPA/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/MC/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/MC/MCParser/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/test/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/utils/FileCheck/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/utils/count/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/utils/not/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Target/X86/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Target/X86/TargetInfo/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Target/X86/AsmPrinter/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Target/X86/AsmParser/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Target/X86/Disassembler/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/ExecutionEngine/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/ExecutionEngine/Interpreter/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/ExecutionEngine/JIT/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Target/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/AsmParser/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/lib/Archive/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/projects/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/tools/cmake_install.cmake")
  INCLUDE("C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/examples/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "C:/Users/skinny/projects/lightspark/lib/llvm-2.7/win32/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
